version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ecommerceDB
    ports:
      - "3307:3306"
  product-management-service:
    image: product-management-service
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/ecommerceDB?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone
