eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
    
server:
  port: 9000
spring:
  application:
    name: user-management-service
  datasource:
    password: root
    url: jdbc:mysql://docker-mysql:3306/ecommerceDB?createDatabaseIfNotExist=true
    username: root
    
  freemarker:
    enabled: true
    suffix: .ftlh
    template-loader-path: classpath:/templates
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
     
twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  trial_number: '+12029466945'
 
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operationsSorter: method   

mail:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}