eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
    
server:
  port: 9001
spring:
  application:
    name: product-management-service
  datasource:
    password: root
    url: jdbc:mysql://docker-mysql:3306/ecommerceDB?createDatabaseIfNotExist=true
    username: root
    
  freemarker:
    enabled: true
    suffix: .ftlh
    template-loader-path: classpath:/templates
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operationsSorter: method    
    