version: '3'
services:
  order-service:
    container_name: order-service
    image: gagan1996/orderservice
    restart: on-failure
    environment:
      PROFILE: "prod"
    ports:
      - 9002:9002
    depends_on:
      - docker-mysql
      - gateway-service
      - eureka-service
      - product-service
  product-service:
    container_name: product-service
    image: gagan1996/productservice
    restart: on-failure
    environment:
      PROFILE: "prod"
    ports:
      - 9001:9001
    depends_on:
      - docker-mysql
      - gateway-service
      - eureka-service
  user-service:
    container_name: user-service
    image: gagan1996/userservice
    restart: on-failure
    environment:
      PROFILE: "prod"
      EMAIL_USERNAME: "dronedeliverysystem@gmail.com"
      EMAIL_PASSWORD: "xywxylpshodcqvda"
      TWILIO_AUTH_TOKEN: "d68a6e74cc9b328528ebbc5f4e752f78"
      TWILIO_ACCOUNT_SID: "AC6eb1cfe9fa0d911513f05515dab83037"
    ports:
      - 9000:9000
    depends_on:
      - docker-mysql
      - gateway-service
      - eureka-service
  gateway-service:
    container_name: gateway-service
    image: gagan1996/gatewayservice
    restart: on-failure
    environment:
      PROFILE: "prod"
    ports:
      - 8000:8000
    depends_on:
      - docker-mysql
      - eureka-service
  eureka-service:
    container_name: eureka-service
    image: gagan1996/eurekaservice
    restart: on-failure
    ports:
      - 8761:8761
    depends_on:
      - docker-mysql
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ecommerceDB"
      MYSQL_HOST: "%"
    ports:
      - 6666:3306