version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ecommerceDB
    ports:
      - "3307:3306"
    networks:
        - estri_gateway_network
  user-management-service:
    image: user-management-service
    ports:
      - "9000:9000"
    networks:
        - estri_gateway_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/ecommerceDB?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone
  product-management-service:
    image: product-management-service
    ports:
      - "9001:9001"
    networks:
        - estri_gateway_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/ecommerceDB?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone
  order-management-service:
    image: order-management-service
    ports:
      - "9002:9002"
    networks:
        - estri_gateway_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/ecommerceDB?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone
  discovery-service:
    image: discovery-service
    ports:
      - "8761:8761"
    networks:
        - estri_gateway_network
    environment:
        EUREKA_APPLICATION_NAME: eureka
        HOST_NAME: localhost
    build:
      context: "./"
      dockerfile: "DockerFile"
  cloud-gateway-service:
    image: cloud-gateway-service
    ports:
      - "8000:8000"
    networks:
        - estri_gateway_network
    environment:
        HOST_NAME: localhost
    build:
      context: "./"
      dockerfile: "DockerFile"
networks: 
  estri_gateway_network: 
